<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign out</name>
   <tag></tag>
   <elementGuidId>bc81964b-1834-4145-a33d-f4a2bbae6407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mectrl_body_signOut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mectrl_body_signOut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cf12c3d-037a-4a2a-be38-3f3e7720ab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mectrl_body_signOut</value>
      <webElementGuid>7c21aa19-2059-482b-90f6-b2782380ecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mectrl_resetStyle mectrl_signout mectrl_truncate</value>
      <webElementGuid>f5ed5e82-fffc-4357-9e09-70bca8372dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sign out of this account</value>
      <webElementGuid>92fd0044-4c4a-43ae-b487-3e644818378a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2dc5d66-1e28-40c5-877b-aee281ce9d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign out</value>
      <webElementGuid>955c8796-7cd4-4c18-9b06-60195f114e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mectrl_body_signOut&quot;)</value>
      <webElementGuid>bdd38e3e-ec55-40f7-8cfd-b4690f06b9d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mectrl_body_signOut']</value>
      <webElementGuid>cc62028f-cbf7-4028-b37a-6cf064582d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review and manage your work or school account information'])[1]/following::button[1]</value>
      <webElementGuid>ce94edd0-9c6e-4179-baf7-5da162362891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View account'])[1]/following::button[1]</value>
      <webElementGuid>f85cfbae-7807-4226-a5be-675164e9ed59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Ctrl + M to navigate to the notification'])[1]/preceding::button[1]</value>
      <webElementGuid>9db7cd53-9600-4b55-b667-85c76a6af1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[1]/preceding::button[1]</value>
      <webElementGuid>3315da5a-917e-4a10-9e14-06b57490b8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign out']/parent::*</value>
      <webElementGuid>85cd3530-af9c-4130-bb81-60a90e4e908f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mectrl_main_body']/div/div/button</value>
      <webElementGuid>57977649-05b9-4cb4-a225-eb894d986ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>e21cc264-2e63-4fbc-ae8b-ef7c6ddf7cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
