<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mk</name>
   <tag></tag>
   <elementGuidId>30c64a93-9e07-41ec-893b-b9cf92214598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mectrl_headerPicture</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mectrl_headerPicture']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53671b39-3a11-4423-88ae-af95f4938d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mectrl_headerPicture</value>
      <webElementGuid>d95e4ed2-332d-4c4a-a8ef-a2a82ebde2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mectrl_profilepic mectrl_profilepic_initials</value>
      <webElementGuid>95e4c04d-45fc-442a-8772-49f17a1628a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>266d4a4f-1dde-473c-b0e5-b165007649b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b483d6de-35d5-47d8-8672-7fe450c12802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mk</value>
      <webElementGuid>fac0f507-6280-4e98-84fa-b9b11b4c0f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mectrl_headerPicture&quot;)</value>
      <webElementGuid>61790c5a-e2c5-482d-af58-aac5f7a267f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mectrl_headerPicture']</value>
      <webElementGuid>65a58035-bd7e-4961-854b-6915ecf317ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account manager for mohit kumar'])[1]/following::div[2]</value>
      <webElementGuid>0cbbb09b-c44e-41d6-bb73-9de8ac17a4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find help and training.'])[1]/following::div[6]</value>
      <webElementGuid>f3043809-534e-4568-ba36-39a6fb92bdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Trial'])[1]/preceding::div[1]</value>
      <webElementGuid>b21eda47-d2a6-4be8-a7af-44806e96e42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mohit kumar'])[1]/preceding::div[4]</value>
      <webElementGuid>5f57be37-8d98-4773-8bb7-8f38ab9e838a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mk']/parent::*</value>
      <webElementGuid>9e72c381-a603-4d4b-8ab8-e3e26907e2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='mectrl_main_trigger']/div/div/div</value>
      <webElementGuid>20312195-bcc9-4e4e-afd7-78f7955c4247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div</value>
      <webElementGuid>8b423d91-287e-451a-9f08-584898d71e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
