<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sign out_AppLandingPage</name>
   <tag></tag>
   <elementGuidId>6e5deca7-60ae-49f1-be9f-66a928167065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AppLandingPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='AppLandingPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>909f4063-1702-4521-84ce-aecbf38f4e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>bce56b5f-d521-489e-9949-99e06b67baa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>7d5abf0c-436e-4a20-abfe-7b051ca1f67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/%7b637851900740000142%7d/webresources/msdyn_appmanagementcontrol</value>
      <webElementGuid>65a40415-b79a-409f-912d-d889db8c9588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-aj pa-as pa-ak </value>
      <webElementGuid>23bc9a22-2dbc-41be-ab7f-04d62d5bcb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppLandingPage&quot;)</value>
      <webElementGuid>aff747fd-0ce1-4883-8e5f-d21418c9372a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='AppLandingPage']</value>
      <webElementGuid>f7b318a4-4c9e-4e79-ad65-fda7a4e6a19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-435']/div/iframe</value>
      <webElementGuid>ef6752a3-f566-4719-be4f-727c92ffc9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6309aecb-e021-4ddb-a723-ae58dfae31e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
