<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1eb11bf6-2376-45bb-9452-6c4d2bdb5c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Dynamics 365 — custom&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AppModuleTileSec_1_Item_1']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32c3e098-6c18-4bc4-ad45-8df511433ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>app-icon</value>
      <webElementGuid>c471f6b3-3f17-433a-90fe-cd94db328dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>msdyn_/Images/Legacy_Crm_Icon.png</value>
      <webElementGuid>ca728ba8-b893-40f2-bd42-9288fd689c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dynamics 365 — custom</value>
      <webElementGuid>1ad66584-4d3d-4f7b-95f1-5c6371f4a2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppModuleTileSec_1_Item_1&quot;)/div[1]/img[1]</value>
      <webElementGuid>0bef1b70-6f72-45c0-a525-4314e331bbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Microsoft 365/iframe_Sign out_AppLandingPage</value>
      <webElementGuid>8e1e783e-f2e8-4e3b-b5d0-b70c2fb86559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='AppModuleTileSec_1_Item_1']/div/img</value>
      <webElementGuid>172b4e48-1d85-45d5-99e2-c82699d1b79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Dynamics 365 — custom']</value>
      <webElementGuid>23b466d0-76bf-4dde-8b09-6ed26ca168dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b7033d3a-b6c6-4e1c-a963-6b9a4e52ac26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
