<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone_id-aa7c154f-e2f8-45db-b7_027664</name>
   <tag></tag>
   <elementGuidId>c0ff2840-89c6-46ed-9cf8-bdbfc0159d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-11-mobilephone4273edbd-ac1d-40d3-9fb2-095c621b552d-mobilephone.fieldControl-phone-text-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53e6ef2f-eb50-461b-a6ff-6e22f2779a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-11-mobilephone4273edbd-ac1d-40d3-9fb2-095c621b552d-mobilephone.fieldControl-phone-text-input</value>
      <webElementGuid>53c5248f-dbac-406e-8b4a-078f524d0871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mobile Phone</value>
      <webElementGuid>cb40d1ab-64a8-4098-a601-6d4fca3953b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>mobilephone.fieldControl-phone-text-input</value>
      <webElementGuid>b8c8905a-2304-4df6-886e-6bf7b417f5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Provide a telephone number</value>
      <webElementGuid>e47541cc-40fa-4ced-9b93-94cb60bd5114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45e31b70-9c37-4840-92b9-41168be2b2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a31e091-5624-45f0-8b5e-a0a1e1eea095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-en pa-rl pa-am pa-bs pa-dp pa-qt pa-rm pa-kt pa-nu pa-rn pa-ro pa-ae pa-af pa-ie pa-cx pa-cb pa-tb pa-tc pa-td pa-te pa-tf pa-sg </value>
      <webElementGuid>fb71fb75-a055-4574-bdf0-fc5b7e36063d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>850ee7ef-70ed-49bd-9f89-48b9b8d20c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-11-mobilephone4273edbd-ac1d-40d3-9fb2-095c621b552d-mobilephone.fieldControl-phone-text-input&quot;)</value>
      <webElementGuid>301312c1-4ba7-4013-b022-affb9aae28d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-11-mobilephone4273edbd-ac1d-40d3-9fb2-095c621b552d-mobilephone.fieldControl-phone-text-input']</value>
      <webElementGuid>9554cce8-30dd-4d4b-9285-9ca7460fd40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-11-mobilephone4273edbd-ac1d-40d3-9fb2-095c621b552d-mobilephone.fieldControl-phone-container']/input</value>
      <webElementGuid>bb4fe1f8-b26d-4c5b-ae6d-3e43fe8a6c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/section/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>b2fc7fa1-e63f-49c3-a4ef-ae97f8cc8e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
