<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_id-aa7c154f-e2f8-45db-b7_bdcdac</name>
   <tag></tag>
   <elementGuidId>7875db3e-42ba-43ae-9954-bf8dea8a9458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-9-companyname4273edbd-ac1d-40d3-9fb2-095c621b552d-companyname.fieldControl-text-box-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c4d387d-dd86-4b09-8652-22b57f53da81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-9-companyname4273edbd-ac1d-40d3-9fb2-095c621b552d-companyname.fieldControl-text-box-text</value>
      <webElementGuid>98e86062-d0ed-4915-988c-77af7e6b5127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Company Name</value>
      <webElementGuid>0e570a59-cee9-41b1-bcfc-dae914cb5456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>companyname.fieldControl-text-box-text</value>
      <webElementGuid>8576244f-8196-4d96-a757-52cc6b705a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c5eadd28-979a-4c6c-85a6-dbb559ba9273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e050fddb-6bfb-4fc1-94b0-b3208521e491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ebbf308-3570-4cd4-bc0f-8d8825edefaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-en pa-rl pa-am pa-bs pa-dp pa-qt pa-rm pa-kt pa-nu pa-rn pa-ro pa-ae pa-af pa-ie pa-cx pa-cb pa-tb pa-tc pa-td pa-te pa-tf pa-sg </value>
      <webElementGuid>af18eb35-f9e2-4ca7-9e84-cc079bc8c148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-9-companyname4273edbd-ac1d-40d3-9fb2-095c621b552d-companyname.fieldControl-text-box-text&quot;)</value>
      <webElementGuid>b0c9fe67-453a-47ea-854f-37bc0504a8fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-9-companyname4273edbd-ac1d-40d3-9fb2-095c621b552d-companyname.fieldControl-text-box-text']</value>
      <webElementGuid>af11661f-bac0-4d26-804a-3292c2dc9e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-9-companyname4273edbd-ac1d-40d3-9fb2-095c621b552d-companyname.fieldControl-text-box-container']/input</value>
      <webElementGuid>c0d1dde3-3444-46f2-888e-edb3eb35b83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>7aef07ba-268d-4018-ba17-5217288cf5a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
