<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Topic_id-aa7c154f-e2f8-45db-b780-a9a8_387019</name>
   <tag></tag>
   <elementGuidId>86c27fae-5f9c-4083-8fc4-0e2e72a55524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-2-subject4273edbd-ac1d-40d3-9fb2-095c621b552d-subject.fieldControl-text-box-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbec0a3b-56ce-4f9a-9bf3-2308c8f646f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-2-subject4273edbd-ac1d-40d3-9fb2-095c621b552d-subject.fieldControl-text-box-text</value>
      <webElementGuid>82ebe3c9-5ea0-4340-a657-47daff6626bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Topic</value>
      <webElementGuid>05106744-e49e-448c-b69d-0c4cbbbfb4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14b9314f-da27-482c-80bb-1119d0a82f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>subject.fieldControl-text-box-text</value>
      <webElementGuid>65c7bff9-2452-45bd-871c-b8e438629a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>f4019586-588b-48a4-8cff-2cc7ee7d1f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d450d2b6-b333-456e-9417-3ea679669ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b739405-5751-4c50-a860-bc768cc5ee68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-en pa-rl pa-am pa-bs pa-dp pa-qt pa-rm pa-kt pa-nu pa-rn pa-ro pa-ae pa-af pa-ie pa-cx pa-cb pa-tb pa-tc pa-td pa-te pa-tf pa-sg </value>
      <webElementGuid>bee47e86-c548-4498-b836-dec912651cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-2-subject4273edbd-ac1d-40d3-9fb2-095c621b552d-subject.fieldControl-text-box-text&quot;)</value>
      <webElementGuid>6416a37a-af46-4e70-a254-f32d5ec1dc9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-2-subject4273edbd-ac1d-40d3-9fb2-095c621b552d-subject.fieldControl-text-box-text']</value>
      <webElementGuid>bd48fabc-8547-431a-9f1f-f7e100b20cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-2-subject4273edbd-ac1d-40d3-9fb2-095c621b552d-subject.fieldControl-text-box-container']/input</value>
      <webElementGuid>8032c164-b655-48bc-a6e3-ab0b43969334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9e112c91-7cd0-43ed-8229-59bfb0eb980f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
