<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Budget Amount_id-aa7c154f-e2f8-45db-b_f558ac</name>
   <tag></tag>
   <elementGuidId>c0cb3afa-0b11-4636-8e39-dd94efe0cfb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-3-budgetamount533b9e00-756b-4312-95a0-dc888637ac78-budgetamount.fieldControl-currency-text-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba1a4430-0fff-4077-9c6f-8d28bbc03f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-3-budgetamount533b9e00-756b-4312-95a0-dc888637ac78-budgetamount.fieldControl-currency-text-input</value>
      <webElementGuid>37c0ae5f-3e2b-4652-9ab6-acebbebe4035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Budget Amount</value>
      <webElementGuid>4a1ce989-ccbb-46fb-88f3-a61eddc8d5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>budgetamount.fieldControl-currency-text-input</value>
      <webElementGuid>c4ed02d1-512f-4283-af7a-cd9d13aee770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d5a85ae-51b9-42e1-9dd9-2e42fdaa33f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b8d6408-3f43-42dd-b56a-a0c1ca5bf345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-en pa-rl pa-am pa-bs pa-dp pa-qt pa-rm pa-kt pa-nu pa-rn pa-ro pa-ae pa-af pa-ie pa-cx pa-cb pa-tb pa-sg </value>
      <webElementGuid>00a3ead2-cf54-4afa-8ef0-824dc517dec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>bb9427cf-1d75-4bf5-a8ec-0ac7a77814cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-3-budgetamount533b9e00-756b-4312-95a0-dc888637ac78-budgetamount.fieldControl-currency-text-input&quot;)</value>
      <webElementGuid>ba643993-7661-4291-ab45-b1360ce4fd21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-3-budgetamount533b9e00-756b-4312-95a0-dc888637ac78-budgetamount.fieldControl-currency-text-input']</value>
      <webElementGuid>40e68593-8f3a-41d9-9036-7318e9e4dc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-3-budgetamount533b9e00-756b-4312-95a0-dc888637ac78']/input</value>
      <webElementGuid>6e4c7e40-221a-43b4-b4e9-a3196bb5069a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3ecafc56-f7dd-46ee-b7e4-286444ff3c0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
