<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_id-aa7c154f-e2f8-45db-b780-_3bfe96</name>
   <tag></tag>
   <elementGuidId>38f4e5d4-e96e-4bcb-9601-ad2ad258c620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-7-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>424fa913-4e55-4f1d-83ae-2721167d4f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-7-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text</value>
      <webElementGuid>dfa81c1f-2785-4a0e-bc3d-7c0432aaa85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>bdf52dae-cb20-4589-9967-a490817d8e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e677b8c7-ebcf-40b6-bb8b-39d3e009b91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>lastname.fieldControl-text-box-text</value>
      <webElementGuid>18597a20-853a-4b9b-a8e5-b02ce7ed623d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f1085b89-b721-4bb5-aa79-22ff68daaa94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83367bb3-d373-4690-9a7c-9f198358c9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>976a4355-6c98-4187-b31b-a987c93c4db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-en pa-rl pa-am pa-bs pa-dp pa-qt pa-rm pa-kt pa-nu pa-rn pa-ro pa-ae pa-af pa-ie pa-cx pa-cb pa-tb pa-tc pa-td pa-te pa-tf pa-sg </value>
      <webElementGuid>434f40ff-0dca-4639-9d42-5bd5c4b0fe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>2ed54115-59c9-41ce-b05f-2e4b410b4c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-7-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text&quot;)</value>
      <webElementGuid>e202e17e-7c28-4b32-8288-c372255775c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-7-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text']</value>
      <webElementGuid>cb2b0883-84ab-4dbe-8dbc-c91ee6c68b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-7-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-container']/input</value>
      <webElementGuid>1633ce3c-0955-4a11-9cad-472f61386516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>e0d42442-3c98-4380-977a-eb2188df5f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
