<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Title_id-aa7c154f-e2f8-45db-b780-_66bb21</name>
   <tag></tag>
   <elementGuidId>3d1461cc-d101-4777-912e-4cdf6bf2bcc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-8-jobtitle4273edbd-ac1d-40d3-9fb2-095c621b552d-jobtitle.fieldControl-text-box-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a591b9b0-0777-4bce-993b-d334779c29b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-8-jobtitle4273edbd-ac1d-40d3-9fb2-095c621b552d-jobtitle.fieldControl-text-box-text</value>
      <webElementGuid>baf5a870-1383-418a-bd08-e2d1212e5fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Job Title</value>
      <webElementGuid>9c7fbc12-4aa8-4f33-b39b-0aae54d38668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>jobtitle.fieldControl-text-box-text</value>
      <webElementGuid>62f6e2f2-ae09-40b9-a9c2-4cd5013ec141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>350f9f9e-f80d-4182-8c15-7bae43f43045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f835bd9e-f17f-44c6-897c-078ae3f1f58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e647c20a-591a-4b85-b55c-b32b7972275d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-en pa-rl pa-am pa-bs pa-dp pa-qt pa-rm pa-kt pa-nu pa-rn pa-ro pa-ae pa-af pa-ie pa-cx pa-cb pa-tb pa-tc pa-td pa-te pa-tf pa-sg </value>
      <webElementGuid>959f3285-96ed-4204-8071-bec3db36a0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>2521eecb-196c-42bf-900c-c891ffc9fa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-8-jobtitle4273edbd-ac1d-40d3-9fb2-095c621b552d-jobtitle.fieldControl-text-box-text&quot;)</value>
      <webElementGuid>fa477fc4-803a-428e-9d68-2bc008335801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-8-jobtitle4273edbd-ac1d-40d3-9fb2-095c621b552d-jobtitle.fieldControl-text-box-text']</value>
      <webElementGuid>f5b4acea-1e4d-40e8-ad17-03f3baa2469b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-8-jobtitle4273edbd-ac1d-40d3-9fb2-095c621b552d-jobtitle.fieldControl-text-box-container']/input</value>
      <webElementGuid>c4622099-c35b-41cf-a941-4efe52019280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>cd0b1c0a-d371-4e98-8c10-e3ad6a7ca9c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
