<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AdvertisementEmployee Refe_e1d32e</name>
   <tag></tag>
   <elementGuidId>f3712a2e-0429-44df-ac0a-60a2b928754a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-5-leadsourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-leadsourcecode.fieldControl-option-set-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>497b9b13-8b48-44db-9373-ca0384952d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-5-leadsourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-leadsourcecode.fieldControl-option-set-select</value>
      <webElementGuid>f04ee73f-9b04-4c04-ac0d-911a2b59bb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Lead Source</value>
      <webElementGuid>ed65277e-4d9b-4ea4-bf7c-549fe9d96ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select--</value>
      <webElementGuid>3e80f27b-c504-46d1-adf6-c3088d026e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>leadsourcecode.fieldControl-option-set-select</value>
      <webElementGuid>37810e4d-c64a-4f7f-bc6b-eff8a74cf185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-sj pa-f pa-am pa-sk pa-sl pa-sm pa-dp pa-qt pa-as pa-cb pa-rm pa-sn pa-so pa-sp pa-sq pa-sr </value>
      <webElementGuid>4ac513a9-4841-492b-8e5b-ccffcf24806e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AdvertisementEmployee ReferralExternal ReferralPartnerPublic RelationsSeminarTrade ShowWebWord of MouthOther</value>
      <webElementGuid>332eeba4-b08c-4d56-8e67-8f7a0865e835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-5-leadsourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-leadsourcecode.fieldControl-option-set-select&quot;)</value>
      <webElementGuid>44c9c580-13db-4aee-b35a-0e257124a432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-5-leadsourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-leadsourcecode.fieldControl-option-set-select']</value>
      <webElementGuid>761e9f18-59be-48f5-a159-874cbf904a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead Source'])[1]/following::select[1]</value>
      <webElementGuid>40f4fdce-2bdb-42da-a33e-00b7f4583a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Timeframe'])[1]/following::select[2]</value>
      <webElementGuid>43e9b9c6-1a1e-4f36-8b1e-ebf9e45c0ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Information'])[1]/preceding::select[1]</value>
      <webElementGuid>425b6ccb-e2db-41b5-ab43-d0cdfaab7ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::select[1]</value>
      <webElementGuid>5e362bdf-8d21-4a15-bd3f-4b84422513a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-5-leadsourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-leadsourcecode.fieldControl-option-set-select-container']/select</value>
      <webElementGuid>176afa1b-1f95-4633-af7b-38df3afa8c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>338c8937-7d7b-41ed-8fa1-8fa68bb6337e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
