<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--ImmediateThis QuarterNext _81daba</name>
   <tag></tag>
   <elementGuidId>ac74e724-e865-4016-bb1f-3f621c37e442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-4-purchasetimeframe3ef39988-22bb-4f0b-bbbe-64b5a3748aee-purchasetimeframe.fieldControl-option-set-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>31c5bbce-8571-4209-b05c-eef35d33f871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-4-purchasetimeframe3ef39988-22bb-4f0b-bbbe-64b5a3748aee-purchasetimeframe.fieldControl-option-set-select</value>
      <webElementGuid>241a12e6-f701-47a9-93b3-ce5ebe536420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Purchase Timeframe</value>
      <webElementGuid>d3b0e106-e801-40b5-949d-e393fbf6767a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select--</value>
      <webElementGuid>20b0abfd-d07f-4d9f-b7e5-01e02f1d0d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>purchasetimeframe.fieldControl-option-set-select</value>
      <webElementGuid>2f657b3e-2888-4320-bb6d-d4ca08fc9e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-sj pa-f pa-am pa-sk pa-sl pa-sm pa-dp pa-qt pa-as pa-cb pa-rm pa-sn pa-so pa-sp pa-sq pa-sr </value>
      <webElementGuid>4243144e-cdf9-4441-9900-df8f6b5db2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--ImmediateThis QuarterNext QuarterThis YearUnknown</value>
      <webElementGuid>a6c460bd-56f4-4619-ac22-bc11c321eadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-4-purchasetimeframe3ef39988-22bb-4f0b-bbbe-64b5a3748aee-purchasetimeframe.fieldControl-option-set-select&quot;)</value>
      <webElementGuid>a5fd06f5-dc2c-466a-bd6c-c8dd77a5c39d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-4-purchasetimeframe3ef39988-22bb-4f0b-bbbe-64b5a3748aee-purchasetimeframe.fieldControl-option-set-select']</value>
      <webElementGuid>07cb5517-b6ef-41eb-a04f-809e39695c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Timeframe'])[1]/following::select[1]</value>
      <webElementGuid>bafa9bbb-a39a-477c-8f85-f100dcdb9425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Budget Amount'])[1]/following::select[1]</value>
      <webElementGuid>76c7c374-c144-4100-838f-a509dd1c2ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead Source'])[1]/preceding::select[1]</value>
      <webElementGuid>cc6991f3-8f11-4e27-aba1-8f9456535b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Information'])[1]/preceding::select[2]</value>
      <webElementGuid>08d29ea1-fbc0-4703-8238-8ffcb1e60c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-aa7c154f-e2f8-45db-b780-a9a8a96332fe-4-purchasetimeframe3ef39988-22bb-4f0b-bbbe-64b5a3748aee-purchasetimeframe.fieldControl-option-set-select-container']/select</value>
      <webElementGuid>a875a2b9-862c-4e77-b1e4-4b2273696c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a8be1bf8-21e2-46f7-befe-44e7b813746c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
