<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delete_1</name>
   <tag></tag>
   <elementGuidId>f093cd41-88f8-42d1-aa38-010a43f6bd96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmButtonText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='confirmButtonText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bfeac0c5-0180-4b64-bc33-7260aa7c070f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmButtonText</value>
      <webElementGuid>75aefb14-f13a-415e-aecb-4753d7834f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-dp pa-ds pa-bs pa-bq pa-e pa-ay </value>
      <webElementGuid>af4e2a3a-8570-4276-83eb-01d1b4a1989e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>4c27f887-fc00-4375-96a3-853d5da4d1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmButtonText&quot;)</value>
      <webElementGuid>67cbf11a-823e-4119-8aff-3794e053fc14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='confirmButtonText']</value>
      <webElementGuid>80aeb607-4f19-48a0-9b44-0933fa20a30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Do you want to delete this Lead? You can', &quot;'&quot;, 't undo this action.')])[1]/following::span[1]</value>
      <webElementGuid>132b978d-f962-41fd-977c-d8b8a46370ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Deletion'])[1]/following::span[3]</value>
      <webElementGuid>63ac1d86-4dd5-4d9e-ae02-9d0a030c4c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[1]</value>
      <webElementGuid>24261c59-f2fa-44f9-b07e-f314cc893955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='confirmButton']/span</value>
      <webElementGuid>484c69b6-0d35-4cd1-bb58-5898b9320ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>f9fab30e-2f08-433f-98b7-776a687f0c85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
